#!/bin/sh
# File: make.template
# Author: Oxnz
# Created
# Description: template file for filetype: [make] with suffix: [make]


#
# %FFILE%
# %USER%, %FDATE%
#

CXXFLAGS	:= -std=c++11 -Wall

all: sparse-dense

sparse-dense: sparse-dense.cpp
